---
abstract: 'Make README.mkdn from POD.'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable-ReadmeMarkdownFromPod
no_index:
  directory:
    - inc
provides:
  Module::Build::Pluggable::ReadmeMarkdownFromPod:
    file: lib/Module/Build/Pluggable/ReadmeMarkdownFromPod.pm
    version: 0.04
requires:
  Class::Accessor::Lite: 0
  Module::Build::Pluggable: 0.09
  Pod::Markdown: 0
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
